Change envVars from array to a map
companyinfo/helm-charts pull request #20
Opened 2023-09-18 09:51 UTC by olenotron

As a user of Helmet, I want to modify specific sections of envVars. However, it's not possible. This is because envVars is an array. Consequently, changing a single key is impossible since Helm overrides the entire set of variables. This PR fixes the open issue https://github.com/companyinfo/helm-charts/issues/19.

The solution involves changing the data type from an array to a map, like this:
```
# Current
envVars:
  - name: FOO
    value: "bar"
  - name: BOB
    value: "alice"

# New
envVars:
  FOO: "bar"
  BOB: "alive"
```

2023-09-18 09:55 UTC, p-afraz requested changes

2023-09-18 09:55 UTC, p-afraz commented on charts/helmet/README.md
> +#### Migrating from previous version
Can you please mention exact versions? Migrating from `0.x` to `1.x` for example.

2023-09-18 10:25 UTC, p-afraz approved these changes, later dismissed

2023-09-21 05:59 UTC, zevisert commented
Will `valuesFrom` still work with this format?

2023-09-21 14:15 UTC, p-afraz commented
> Will `valuesFrom` still work with this format?

nice catch! this is a fix we can implement to support both cases:
```
envVars:
  FOO: "bar"
  BOB: 
    valueFrom:
      configMapKeyRef:
        name: "foo"
        key: "bar"
```

What do you think?

2023-09-21 16:20 UTC, zevisert commented
@p-afraz Yeah, that format seems logical. Looking into the changes here now, the new `helmet.dictToArray` helper needs to be updated to support that.

2023-10-09 13:19 UTC, closed without merging